/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author ADMIN
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlmain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Lpassword = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        Lusername1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        BttnRecruit = new javax.swing.JLabel();
        showpass2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlmain.setBackground(new java.awt.Color(255, 206, 109));
        pnlmain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 174, 239));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pnlmain.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText(" Log in to Your Account ");
        pnlmain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 51, 420, -1));

        jLabel5.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Welcome! Please enter your details");
        pnlmain.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 87, 310, 16));

        Lpassword.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lpassword.setForeground(new java.awt.Color(51, 51, 51));
        Lpassword.setText("Password");
        pnlmain.add(Lpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 234, 90, -1));

        txtusername.setBackground(new java.awt.Color(153, 153, 153));
        pnlmain.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 173, 370, 55));

        Lusername1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lusername1.setForeground(new java.awt.Color(51, 51, 51));
        Lusername1.setText("Username");
        pnlmain.add(Lusername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 148, 90, -1));

        jPasswordField1.setBackground(new java.awt.Color(153, 153, 153));
        pnlmain.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 259, 370, 53));

        jToggleButton1.setBackground(new java.awt.Color(51, 51, 51));
        jToggleButton1.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jToggleButton1.setText("Login");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        pnlmain.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 367, 370, 48));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Dont have an account?");
        pnlmain.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, -1, -1));

        BttnRecruit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BttnRecruit.setForeground(new java.awt.Color(51, 51, 51));
        BttnRecruit.setText("Register Now!");
        BttnRecruit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BttnRecruitMouseClicked(evt);
            }
        });
        pnlmain.add(BttnRecruit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 110, -1));

        showpass2.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        showpass2.setForeground(new java.awt.Color(51, 51, 51));
        showpass2.setText("Show Password");
        showpass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpass2ActionPerformed(evt);
            }
        });
        pnlmain.add(showpass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void BttnRecruitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BttnRecruitMouseClicked
//        Register reg = new Register();
//        reg.setVisible(true);
//        dispose();
    }//GEN-LAST:event_BttnRecruitMouseClicked

    private void showpass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpass2ActionPerformed
        if(showpass.isSelected()){
            jpassword.setEchoChar((char)0); //I reveal ang password
        }else {
            jpassword.setEchoChar('*');//Taguan ang password
        }
    }//GEN-LAST:event_showpass2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BttnRecruit;
    private javax.swing.JLabel Lpassword;
    private javax.swing.JLabel Lusername1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel pnlmain;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JCheckBox showpass1;
    private javax.swing.JCheckBox showpass2;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
